# Generated by Django 5.1 on 2024-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0004_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('bio', models.TextField()),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
