# Generated by Django 5.1 on 2024-09-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0008_person_aadhaar_no_person_address_person_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
    ]
