# Generated by Django 5.1 on 2024-09-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0010_volunteer_address_volunteer_dob_volunteer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
