# Generated by Django 5.1 on 2024-09-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0018_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='donate',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
