# Generated by Django 5.1 on 2024-09-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0019_donations_alter_donate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/donors/'),
        ),
    ]
