# Generated by Django 5.1 on 2024-09-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0021_alter_donations_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_name', models.CharField(blank=True, max_length=30, null=True)),
                ('eve_date', models.DateField(blank=True, null=True)),
                ('eve_photo', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('eve_caption', models.CharField(blank=True, max_length=50, null=True)),
                ('eve_descr', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
