# Generated by Django 5.1 on 2024-09-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0025_remove_volunteer_dob_remove_volunteer_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
