# Generated by Django 5.1 on 2024-09-20 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0029_remove_donations_cause_person_failed_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='person',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='person',
            name='otp_created_at',
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart_charity.person')),
            ],
        ),
    ]
