# Generated by Django 5.1 on 2024-09-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0030_remove_person_failed_attempts_remove_person_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='cause',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='heart_charity.cause'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='donors/'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='causes/'),
        ),
        migrations.DeleteModel(
            name='OTPModel',
        ),
    ]
