# Generated by Django 5.1 on 2024-09-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0032_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
