# Generated by Django 5.1 on 2024-10-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0033_delete_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='work',
            name='raised',
        ),
    ]
