# Generated by Django 5.1 on 2024-10-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0035_alter_person_aadhaar_no_alter_person_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dependent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='it_return',
            field=models.CharField(max_length=100),
        ),
    ]
