# Generated by Django 5.1 on 2024-10-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0039_person_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='last_updated',
        ),
    ]
