# Generated by Django 5.1 on 2024-10-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0040_remove_person_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donations',
        ),
    ]
